//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neo.Gui.Base.Globalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Neo.Gui.Base.Globalization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEO.
        /// </summary>
        public static string AboutMessage {
            get {
                return ResourceManager.GetString("AboutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _About NEO.
        /// </summary>
        public static string AboutNeoMenuHeader {
            get {
                return ResourceManager.GetString("AboutNeoMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        public static string AboutVersion {
            get {
                return ResourceManager.GetString("AboutVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accent.
        /// </summary>
        public static string Accent {
            get {
                return ResourceManager.GetString("Accent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Details.
        /// </summary>
        public static string AccountDetailsTitle {
            get {
                return ResourceManager.GetString("AccountDetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts.
        /// </summary>
        public static string Accounts {
            get {
                return ResourceManager.GetString("Accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to add smart contract, corresponding private key missing in this wallet..
        /// </summary>
        public static string AddContractFailedMessage {
            get {
                return ResourceManager.GetString("AddContractFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad_vanced.
        /// </summary>
        public static string AdvancedMenuHeader {
            get {
                return ResourceManager.GetString("AdvancedMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        public static string Appearance {
            get {
                return ResourceManager.GetString("Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset.
        /// </summary>
        public static string Asset {
            get {
                return ResourceManager.GetString("Asset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Details.
        /// </summary>
        public static string AssetDetails {
            get {
                return ResourceManager.GetString("AssetDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset D_istribution….
        /// </summary>
        public static string AssetDistributionMenuHeader {
            get {
                return ResourceManager.GetString("AssetDistributionMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Distribution.
        /// </summary>
        public static string AssetDistributionTitle {
            get {
                return ResourceManager.GetString("AssetDistributionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset ID.
        /// </summary>
        public static string AssetId {
            get {
                return ResourceManager.GetString("AssetId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset _Registration….
        /// </summary>
        public static string AssetRegistrationMenuHeader {
            get {
                return ResourceManager.GetString("AssetRegistrationMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Registration.
        /// </summary>
        public static string AssetRegistrationTitle {
            get {
                return ResourceManager.GetString("AssetRegistrationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets.
        /// </summary>
        public static string Assets {
            get {
                return ResourceManager.GetString("Assets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets the counterparty will acquire.
        /// </summary>
        public static string AssetsTheCounterpartyWillAcquire {
            get {
                return ResourceManager.GetString("AssetsTheCounterpartyWillAcquire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets you will acquire.
        /// </summary>
        public static string AssetsYouWillAcquire {
            get {
                return ResourceManager.GetString("AssetsYouWillAcquire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Type.
        /// </summary>
        public static string AssetType {
            get {
                return ResourceManager.GetString("AssetType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        public static string Available {
            get {
                return ResourceManager.GetString("Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        public static string Balance {
            get {
                return ResourceManager.GetString("Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Style.
        /// </summary>
        public static string BaseStyle {
            get {
                return ResourceManager.GetString("BaseStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookkeeper.
        /// </summary>
        public static string Bookkeeper {
            get {
                return ResourceManager.GetString("Bookkeeper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broadcast.
        /// </summary>
        public static string Broadcast {
            get {
                return ResourceManager.GetString("Broadcast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulk Pay.
        /// </summary>
        public static string BulkPay {
            get {
                return ResourceManager.GetString("BulkPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Candidates.
        /// </summary>
        public static string Candidates {
            get {
                return ResourceManager.GetString("Candidates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate Application.
        /// </summary>
        public static string CertificateApplicationTitle {
            get {
                return ResourceManager.GetString("CertificateApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change logs.
        /// </summary>
        public static string ChangeLogs {
            get {
                return ResourceManager.GetString("ChangeLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Pa_ssword….
        /// </summary>
        public static string ChangePasswordMenuHeader {
            get {
                return ResourceManager.GetString("ChangePasswordMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password successful..
        /// </summary>
        public static string ChangePasswordSuccessful {
            get {
                return ResourceManager.GetString("ChangePasswordSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePasswordTitle {
            get {
                return ResourceManager.GetString("ChangePasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Check for Help.
        /// </summary>
        public static string CheckForHelpMenuHeader {
            get {
                return ResourceManager.GetString("CheckForHelpMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim All.
        /// </summary>
        public static string ClaimAll {
            get {
                return ResourceManager.GetString("ClaimAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Close Wallet….
        /// </summary>
        public static string CloseWalletMenuHeader {
            get {
                return ResourceManager.GetString("CloseWalletMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Parameters.
        /// </summary>
        public static string ContractParameters {
            get {
                return ResourceManager.GetString("ContractParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Copy to Clipboard.
        /// </summary>
        public static string CopyToClipboardMenuHeader {
            get {
                return ResourceManager.GetString("CopyToClipboardMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Copy TXID.
        /// </summary>
        public static string CopyTxIdMenuHeader {
            get {
                return ResourceManager.GetString("CopyTxIdMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counterparty request.
        /// </summary>
        public static string CounterpartyRequest {
            get {
                return ResourceManager.GetString("CounterpartyRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Contract _Address.
        /// </summary>
        public static string CreateContractAddressMenuHeader {
            get {
                return ResourceManager.GetString("CreateContractAddressMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Lock Account.
        /// </summary>
        public static string CreateLockAccountTitle {
            get {
                return ResourceManager.GetString("CreateLockAccountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi-Signature.
        /// </summary>
        public static string CreateMultiSigContractTitle {
            get {
                return ResourceManager.GetString("CreateMultiSigContractTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create _New Address.
        /// </summary>
        public static string CreateNewAddressMenuHeader {
            get {
                return ResourceManager.GetString("CreateNewAddressMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Wallet.
        /// </summary>
        public static string CreateWalletTitle {
            get {
                return ResourceManager.GetString("CreateWalletTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Value.
        /// </summary>
        public static string CurrentValue {
            get {
                return ResourceManager.GetString("CurrentValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string Custom {
            get {
                return ResourceManager.GetString("Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Custom….
        /// </summary>
        public static string CustomMenuHeader {
            get {
                return ResourceManager.GetString("CustomMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string DeleteAddressConfirmationCaption {
            get {
                return ResourceManager.GetString("DeleteAddressConfirmationCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upon deletion, assets in these addresses will be permanently lost, are you sure to proceed?.
        /// </summary>
        public static string DeleteAddressConfirmationMessage {
            get {
                return ResourceManager.GetString("DeleteAddressConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets cannot be recovered once deleted, are you sure to delete the assets?.
        /// </summary>
        public static string DeleteAssetConfirmationMessage {
            get {
                return ResourceManager.GetString("DeleteAssetConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string DeleteConfirmation {
            get {
                return ResourceManager.GetString("DeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Delete….
        /// </summary>
        public static string DeleteMenuHeader {
            get {
                return ResourceManager.GetString("DeleteMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deploy.
        /// </summary>
        public static string Deploy {
            get {
                return ResourceManager.GetString("Deploy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Deploy Contract….
        /// </summary>
        public static string DeployContractMenuHeader {
            get {
                return ResourceManager.GetString("DeployContractMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deploy Contract.
        /// </summary>
        public static string DeployContractTitle {
            get {
                return ResourceManager.GetString("DeployContractTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer _Tools.
        /// </summary>
        public static string DeveloperToolsMenuHeader {
            get {
                return ResourceManager.GetString("DeveloperToolsMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer Tools.
        /// </summary>
        public static string DeveloperToolsTitle {
            get {
                return ResourceManager.GetString("DeveloperToolsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribution.
        /// </summary>
        public static string Distribution {
            get {
                return ResourceManager.GetString("Distribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download New Version.
        /// </summary>
        public static string DownloadNewVersion {
            get {
                return ResourceManager.GetString("DownloadNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Array.
        /// </summary>
        public static string EditArray {
            get {
                return ResourceManager.GetString("EditArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Election….
        /// </summary>
        public static string ElectionMenuHeader {
            get {
                return ResourceManager.GetString("ElectionMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Election.
        /// </summary>
        public static string ElectionTitle {
            get {
                return ResourceManager.GetString("ElectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter remark here, which will be recorded on the blockchain.
        /// </summary>
        public static string EnterRemarkMessage {
            get {
                return ResourceManager.GetString("EnterRemarkMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Remark.
        /// </summary>
        public static string EnterRemarkTitle {
            get {
                return ResourceManager.GetString("EnterRemarkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution terminated in fault state..
        /// </summary>
        public static string ExecutionFailed {
            get {
                return ResourceManager.GetString("ExecutionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_xit.
        /// </summary>
        public static string ExitMenuHeader {
            get {
                return ResourceManager.GetString("ExitMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired.
        /// </summary>
        public static string ExpiredCertificate {
            get {
                return ResourceManager.GetString("ExpiredCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        public static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fee.
        /// </summary>
        public static string Fee {
            get {
                return ResourceManager.GetString("Fee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Unspent Coins.
        /// </summary>
        public static string FindUnspentCoins {
            get {
                return ResourceManager.GetString("FindUnspentCoins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function.
        /// </summary>
        public static string Function {
            get {
                return ResourceManager.GetString("Function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _GAS Claim….
        /// </summary>
        public static string GasClaimMenuHeader {
            get {
                return ResourceManager.GetString("GasClaimMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GAS Claim.
        /// </summary>
        public static string GasClaimTitle {
            get {
                return ResourceManager.GetString("GasClaimTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Parameters Context.
        /// </summary>
        public static string GetParametersContext {
            get {
                return ResourceManager.GetString("GetParametersContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to neo-gui.
        /// </summary>
        public static string GuiTitle {
            get {
                return ResourceManager.GetString("GuiTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height:.
        /// </summary>
        public static string HeightHeading {
            get {
                return ResourceManager.GetString("HeightHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Help.
        /// </summary>
        public static string HelpMenuHeader {
            get {
                return ResourceManager.GetString("HelpMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight.
        /// </summary>
        public static string Highlight {
            get {
                return ResourceManager.GetString("Highlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Custom Contract.
        /// </summary>
        public static string ImportCustomContractTitle {
            get {
                return ResourceManager.GetString("ImportCustomContractTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import from _Certificate….
        /// </summary>
        public static string ImportFromCertificateMenuHeader {
            get {
                return ResourceManager.GetString("ImportFromCertificateMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import from _WIF….
        /// </summary>
        public static string ImportFromWifMenuHeader {
            get {
                return ResourceManager.GetString("ImportFromWifMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Import.
        /// </summary>
        public static string ImportMenuHeader {
            get {
                return ResourceManager.GetString("ImportMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Private Key.
        /// </summary>
        public static string ImportPrivateKeyTitle {
            get {
                return ResourceManager.GetString("ImportPrivateKeyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Watch-Only Address.
        /// </summary>
        public static string ImportWatchOnlyAddress {
            get {
                return ResourceManager.GetString("ImportWatchOnlyAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Watch-Only _Address….
        /// </summary>
        public static string ImportWatchOnlyAddressMenuHeader {
            get {
                return ResourceManager.GetString("ImportWatchOnlyAddressMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction initiated, but the signature is incomplete..
        /// </summary>
        public static string IncompletedSignatureMessage {
            get {
                return ResourceManager.GetString("IncompletedSignatureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomplete signature.
        /// </summary>
        public static string IncompletedSignatureTitle {
            get {
                return ResourceManager.GetString("IncompletedSignatureTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initiate.
        /// </summary>
        public static string InitiateRequest {
            get {
                return ResourceManager.GetString("InitiateRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initiate tx. request.
        /// </summary>
        public static string InitiateTxRequest {
            get {
                return ResourceManager.GetString("InitiateTxRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        public static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have cancelled the certificate installation..
        /// </summary>
        public static string InstallCertificateCancel {
            get {
                return ResourceManager.GetString("InstallCertificateCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install the certificate.
        /// </summary>
        public static string InstallCertificateCaption {
            get {
                return ResourceManager.GetString("InstallCertificateCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEO must install Onchain root certificate to validate assets on the blockchain, install it now?.
        /// </summary>
        public static string InstallCertificateText {
            get {
                return ResourceManager.GetString("InstallCertificateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient funds, transaction cannot be initiated..
        /// </summary>
        public static string InsufficientFunds {
            get {
                return ResourceManager.GetString("InsufficientFunds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid.
        /// </summary>
        public static string InvalidCertificate {
            get {
                return ResourceManager.GetString("InvalidCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoke.
        /// </summary>
        public static string Invoke {
            get {
                return ResourceManager.GetString("Invoke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I_nvoke Contract….
        /// </summary>
        public static string InvokeContractMenuHeader {
            get {
                return ResourceManager.GetString("InvokeContractMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoke Contract.
        /// </summary>
        public static string InvokeContractTitle {
            get {
                return ResourceManager.GetString("InvokeContractTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issued.
        /// </summary>
        public static string Issued {
            get {
                return ResourceManager.GetString("Issued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issuer.
        /// </summary>
        public static string Issuer {
            get {
                return ResourceManager.GetString("Issuer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Lock….
        /// </summary>
        public static string LockMenuHeader {
            get {
                return ResourceManager.GetString("LockMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge.
        /// </summary>
        public static string Merge {
            get {
                return ResourceManager.GetString("Merge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge tx. request.
        /// </summary>
        public static string MergeTxRequest {
            get {
                return ResourceManager.GetString("MergeTxRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata.
        /// </summary>
        public static string Metadata {
            get {
                return ResourceManager.GetString("Metadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migrate Wallet.
        /// </summary>
        public static string MigrateWalletCaption {
            get {
                return ResourceManager.GetString("MigrateWalletCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening wallet files in older versions, update to newest format?
        ///Note: updated files cannot be openned by clients in older versions!.
        /// </summary>
        public static string MigrateWalletMessage {
            get {
                return ResourceManager.GetString("MigrateWalletMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallet files relocated. Old files have been auto-saved at: .
        /// </summary>
        public static string MigrateWalletSucceedMessage {
            get {
                return ResourceManager.GetString("MigrateWalletSucceedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min. Signature Number.
        /// </summary>
        public static string MinimumSignatureNumber {
            get {
                return ResourceManager.GetString("MinimumSignatureNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Multi-Signature….
        /// </summary>
        public static string MultiSignatureMenuHeader {
            get {
                return ResourceManager.GetString("MultiSignatureMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My request.
        /// </summary>
        public static string MyTradeRequest {
            get {
                return ResourceManager.GetString("MyTradeRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Needs Storage.
        /// </summary>
        public static string NeedsStorage {
            get {
                return ResourceManager.GetString("NeedsStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEP-5 Contracts List.
        /// </summary>
        public static string NEP5ContractsList {
            get {
                return ResourceManager.GetString("NEP5ContractsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newest Version.
        /// </summary>
        public static string NewestVersion {
            get {
                return ResourceManager.GetString("NewestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Value.
        /// </summary>
        public static string NewValue {
            get {
                return ResourceManager.GetString("NewValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _New Wallet….
        /// </summary>
        public static string NewWalletMenuHeader {
            get {
                return ResourceManager.GetString("NewWalletMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-Standard.
        /// </summary>
        public static string NonStandard {
            get {
                return ResourceManager.GetString("NonStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not evaluated.
        /// </summary>
        public static string NotEvaluated {
            get {
                return ResourceManager.GetString("NotEvaluated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected:.
        /// </summary>
        public static string NumberOfConnectionsHeading {
            get {
                return ResourceManager.GetString("NumberOfConnectionsHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Official Web.
        /// </summary>
        public static string OfficialWeb {
            get {
                return ResourceManager.GetString("OfficialWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Official _Web.
        /// </summary>
        public static string OfficialWebMenuHeader {
            get {
                return ResourceManager.GetString("OfficialWebMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password.
        /// </summary>
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open Wallet….
        /// </summary>
        public static string OpenWalletMenuHeader {
            get {
                return ResourceManager.GetString("OpenWalletMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Wallet.
        /// </summary>
        public static string OpenWalletTitle {
            get {
                return ResourceManager.GetString("OpenWalletTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization.
        /// </summary>
        public static string Organization {
            get {
                return ResourceManager.GetString("Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        public static string Owner {
            get {
                return ResourceManager.GetString("Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter List.
        /// </summary>
        public static string ParameterList {
            get {
                return ResourceManager.GetString("ParameterList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        public static string Parameters {
            get {
                return ResourceManager.GetString("Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Incorrect.
        /// </summary>
        public static string PasswordIncorrect {
            get {
                return ResourceManager.GetString("PasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        public static string Payment {
            get {
                return ResourceManager.GetString("Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay to.
        /// </summary>
        public static string PayTo {
            get {
                return ResourceManager.GetString("PayTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precision.
        /// </summary>
        public static string Precision {
            get {
                return ResourceManager.GetString("Precision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private Key.
        /// </summary>
        public static string PrivateKey {
            get {
                return ResourceManager.GetString("PrivateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public Key.
        /// </summary>
        public static string PublicKey {
            get {
                return ResourceManager.GetString("PublicKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public Key List.
        /// </summary>
        public static string PublicKeyList {
            get {
                return ResourceManager.GetString("PublicKeyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebuild _Index.
        /// </summary>
        public static string RebuildIndexMenuHeader {
            get {
                return ResourceManager.GetString("RebuildIndexMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipient List.
        /// </summary>
        public static string RecipientList {
            get {
                return ResourceManager.GetString("RecipientList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redeem Script.
        /// </summary>
        public static string RedeemScript {
            get {
                return ResourceManager.GetString("RedeemScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-Enter Password.
        /// </summary>
        public static string ReEnterPassword {
            get {
                return ResourceManager.GetString("ReEnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refuse.
        /// </summary>
        public static string Refuse {
            get {
                return ResourceManager.GetString("Refuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related Account.
        /// </summary>
        public static string RelatedAccount {
            get {
                return ResourceManager.GetString("RelatedAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data broadcast success, the hash is shown as follows:.
        /// </summary>
        public static string RelaySuccessText {
            get {
                return ResourceManager.GetString("RelaySuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broadcast Success.
        /// </summary>
        public static string RelaySuccessTitle {
            get {
                return ResourceManager.GetString("RelaySuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw:.
        /// </summary>
        public static string RelayTitle {
            get {
                return ResourceManager.GetString("RelayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remark.
        /// </summary>
        public static string Remark {
            get {
                return ResourceManager.GetString("Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repair mode.
        /// </summary>
        public static string RepairMode {
            get {
                return ResourceManager.GetString("RepairMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request _Certificate….
        /// </summary>
        public static string RequestCertificateMenuHeader {
            get {
                return ResourceManager.GetString("RequestCertificateMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        public static string Results {
            get {
                return ResourceManager.GetString("Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Type.
        /// </summary>
        public static string ReturnType {
            get {
                return ResourceManager.GetString("ReturnType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script.
        /// </summary>
        public static string Script {
            get {
                return ResourceManager.GetString("Script", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script Hash.
        /// </summary>
        public static string ScriptHash {
            get {
                return ResourceManager.GetString("ScriptHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Certificate.
        /// </summary>
        public static string SelectCertificateTitle {
            get {
                return ResourceManager.GetString("SelectCertificateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction sent, TXID:.
        /// </summary>
        public static string SendTxSucceedMessage {
            get {
                return ResourceManager.GetString("SendTxSucceedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction successful.
        /// </summary>
        public static string SendTxSucceedTitle {
            get {
                return ResourceManager.GetString("SendTxSucceedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Parameters.
        /// </summary>
        public static string SetParametersTitle {
            get {
                return ResourceManager.GetString("SetParametersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Settings….
        /// </summary>
        public static string SettingsMenuHeader {
            get {
                return ResourceManager.GetString("SettingsMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup Outputs.
        /// </summary>
        public static string SetupOutputs {
            get {
                return ResourceManager.GetString("SetupOutputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature.
        /// </summary>
        public static string Signature {
            get {
                return ResourceManager.GetString("Signature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Signature….
        /// </summary>
        public static string SignatureMenuHeader {
            get {
                return ResourceManager.GetString("SignatureMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The private key that can sign the data is not found..
        /// </summary>
        public static string SigningFailedKeyNotFoundMessage {
            get {
                return ResourceManager.GetString("SigningFailedKeyNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must input JSON object pending signature data..
        /// </summary>
        public static string SigningFailedNoDataMessage {
            get {
                return ResourceManager.GetString("SigningFailedNoDataMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        public static string Standard {
            get {
                return ResourceManager.GetString("Standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string SystemIssuer {
            get {
                return ResourceManager.GetString("SystemIssuer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total limit.
        /// </summary>
        public static string TotalLimit {
            get {
                return ResourceManager.GetString("TotalLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation failed, the counterparty falsified the transaction content!.
        /// </summary>
        public static string TradeFailedFakeDataMessage {
            get {
                return ResourceManager.GetString("TradeFailedFakeDataMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation failed, the counterparty generated illegal transaction content!.
        /// </summary>
        public static string TradeFailedInvalidDataMessage {
            get {
                return ResourceManager.GetString("TradeFailedInvalidDataMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation failed, invalid transaction or unsynchronized blockchain, please try again when synchronized!.
        /// </summary>
        public static string TradeFailedNoSyncMessage {
            get {
                return ResourceManager.GetString("TradeFailedNoSyncMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need Signature.
        /// </summary>
        public static string TradeNeedSignatureCaption {
            get {
                return ResourceManager.GetString("TradeNeedSignatureCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction generated, please send the following information to the counterparty for signing:.
        /// </summary>
        public static string TradeNeedSignatureMessage {
            get {
                return ResourceManager.GetString("TradeNeedSignatureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade Request.
        /// </summary>
        public static string TradeRequestCreatedCaption {
            get {
                return ResourceManager.GetString("TradeRequestCreatedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction request generated, please send it to the counterparty or merge it with the counterparty&apos;s request..
        /// </summary>
        public static string TradeRequestCreatedMessage {
            get {
                return ResourceManager.GetString("TradeRequestCreatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade Success.
        /// </summary>
        public static string TradeSuccessCaption {
            get {
                return ResourceManager.GetString("TradeSuccessCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction sent, this is the TXID:.
        /// </summary>
        public static string TradeSuccessMessage {
            get {
                return ResourceManager.GetString("TradeSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction.
        /// </summary>
        public static string TradeTitle {
            get {
                return ResourceManager.GetString("TradeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction ID.
        /// </summary>
        public static string TransactionId {
            get {
                return ResourceManager.GetString("TransactionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Transaction.
        /// </summary>
        public static string TransactionMenuHeader {
            get {
                return ResourceManager.GetString("TransactionMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Remark.
        /// </summary>
        public static string TransactionRemark {
            get {
                return ResourceManager.GetString("TransactionRemark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transactions.
        /// </summary>
        public static string Transactions {
            get {
                return ResourceManager.GetString("Transactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transactions (_X)….
        /// </summary>
        public static string TransactionsMenuHeader {
            get {
                return ResourceManager.GetString("TransactionsMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Type.
        /// </summary>
        public static string TransactionType {
            get {
                return ResourceManager.GetString("TransactionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Verification.
        /// </summary>
        public static string TransactionVerificationTitle {
            get {
                return ResourceManager.GetString("TransactionVerificationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer.
        /// </summary>
        public static string Transfer {
            get {
                return ResourceManager.GetString("Transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Transfer….
        /// </summary>
        public static string TransferMenuHeader {
            get {
                return ResourceManager.GetString("TransferMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tx Builder.
        /// </summary>
        public static string TxBuilder {
            get {
                return ResourceManager.GetString("TxBuilder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unavailable.
        /// </summary>
        public static string Unavailable {
            get {
                return ResourceManager.GetString("Unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unconfirmed.
        /// </summary>
        public static string Unconfirmed {
            get {
                return ResourceManager.GetString("Unconfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown issuer.
        /// </summary>
        public static string UnknownIssuer {
            get {
                return ResourceManager.GetString("UnknownIssuer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock Date.
        /// </summary>
        public static string UnlockDate {
            get {
                return ResourceManager.GetString("UnlockDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blockchain unsynchronized, transaction cannot be sent..
        /// </summary>
        public static string UnsynchronizedBlock {
            get {
                return ResourceManager.GetString("UnsynchronizedBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Available.
        /// </summary>
        public static string UpdateTitle {
            get {
                return ResourceManager.GetString("UpdateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate.
        /// </summary>
        public static string Validate {
            get {
                return ResourceManager.GetString("Validate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View _Certificate.
        /// </summary>
        public static string ViewCertificateMenuHeader {
            get {
                return ResourceManager.GetString("ViewCertificateMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View C_ontract.
        /// </summary>
        public static string ViewContractMenuHeader {
            get {
                return ResourceManager.GetString("ViewContractMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Contract.
        /// </summary>
        public static string ViewContractTitle {
            get {
                return ResourceManager.GetString("ViewContractTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View _Private Key.
        /// </summary>
        public static string ViewPrivateKeyMenuHeader {
            get {
                return ResourceManager.GetString("ViewPrivateKeyMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Private Key.
        /// </summary>
        public static string ViewPrivateKeyTitle {
            get {
                return ResourceManager.GetString("ViewPrivateKeyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Vote….
        /// </summary>
        public static string VoteMenuHeader {
            get {
                return ResourceManager.GetString("VoteMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voting.
        /// </summary>
        public static string VotingTitle {
            get {
                return ResourceManager.GetString("VotingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for next block.
        /// </summary>
        public static string WaitingForNextBlock {
            get {
                return ResourceManager.GetString("WaitingForNextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallet File.
        /// </summary>
        public static string WalletFile {
            get {
                return ResourceManager.GetString("WalletFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Wallet.
        /// </summary>
        public static string WalletMenuHeader {
            get {
                return ResourceManager.GetString("WalletMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch Only.
        /// </summary>
        public static string WatchOnly {
            get {
                return ResourceManager.GetString("WatchOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WIF Private Key.
        /// </summary>
        public static string WifPrivateKey {
            get {
                return ResourceManager.GetString("WifPrivateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window Border.
        /// </summary>
        public static string WindowBorder {
            get {
                return ResourceManager.GetString("WindowBorder", resourceCulture);
            }
        }
    }
}
